---
id: lilo-20240128
base_name: upgrade-debian
tags:
- debian
presentation_date: '2024-01-28'
presentation_start_time:
presentation_end_time:
version: 2024.1.28.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
source_code_uri:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
